[workspace]
channels = ["conda-forge", "bioconda"]
name = "ngs-quality-control-for-blog-example"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.33,<2"
